part of auth_actions;

@freezed
abstract class UpdateRegisterInfo with _$UpdateRegisterInfo implements AppAction {
  const factory UpdateRegisterInfo({
    String email,
    String password,
    String username,
    DateTime birthDate,
    String location,
    String cars,
    String photoUrl,
    String firstName,
    String lastName,
    String serviceName,
    String serviceLocation,
    String servicePhone,
    bool isAutoElectricianService,
    bool isCarBodyRepairsService,
    bool isCarDealershipService,
    bool isCarDiagnosticsService,
    bool isCarInssuranceService,
    bool isCarRentalService,
    bool isDetailingService,
    bool isEngineDecarbonizationService,
    bool isParticleFilterCleaningService,
    bool isServiceAndRepairs,
    bool isTowingService,
    bool isTuningService,
    bool isVulcanisingService,
    bool isWrappingService,
    String serviceDescription,
    String mondayServiceHours,
    String tuesdayServiceHours,
    String wednesdayServiceHours,
    String thursdayServiceHours,
    String fridayServiceHours,
    String saturdayServiceHours,
    String sundayServiceHours,
    bool isServiceAvailable,
    String serviceCoverPhotoUrl,
    String serviceProfilePhotoUrl,
  }) = UpdateRegisterInfo$;
}
